scripts: add build script and hook it up with init
This script will build all libraries needed to run
FRC development with Gazebo simulation. For now it builds
the WPILib from source with makeSim flag so that
we get the Gazebo HAL extensions and Gazebo
plugins

Signed-off-by: Ilija Hadzic <ilijahadzic@gmail.com>

diff --git a/scripts/frc_gaz_init b/scripts/frc_gaz_init
--- a/scripts/frc_gaz_init
+++ b/scripts/frc_gaz_init
@@ -22,3 +22,9 @@ if [ $? -ne 0 ]; then
     echo "ERROR: failed to clone allspilib repository. Please check your Internet connection and make sure the wpilibsuite/allwpilib.git still exists on Github. Aborting!"
     exit 1
 fi
+
+$FRC_ROOT/frc_gazebo_2021/scripts/frc_gaz_build
+if [ $? -ne 0 ]; then
+    echo "ERROR: failed to build WPILib, please debug it"
+    exit 1
+fi
